import Head from 'next/head';
import useSWR from 'swr';
import { useRef, useState } from 'react';
import styles from '../styles/Home.module.css';

const fetcher = (url) => fetch(url).then((res) => res.json());

export default function Home() {
  const ref = useRef(null);
  const { data: todos, error, mutate } = useSWR('/api/todos', fetcher);
  const handleAdd = async () => {
    const newTodo = await fetch(
      '/api/todos',
      {
        method: 'POST',
        body: JSON.stringify({
          title: ref.current.value,
        }),
      },
      { rollbackOnError: true, revalidate: true }
    ).then((res) => res.json());
    console.log(todos);
    mutate([newTodo, ...todos]);
    ref.current.value = '';
  };
  console.log(todos);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>ToDos</h1>
      <input placeholder="ToDo" ref={ref} />
      <button onClick={handleAdd}>Add</button>
      {todos && (
        <ul>
          {todos.map((todo) => (
            <li key={todo.id}>
              <span>{todo.title}</span>
              <button>Delete</button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
